input:
  whatever:
    required: true
runs:
  using: composite
  steps:

  - name: Echo whatever
    env:
      whatever: ${{ inputs.whatever }}
    run: |
      echo "The value of whatever is $whatever"
      echo whatever=$whatever >> $GITHUB_ENV
      echo "Now $whatever is also part of your env"
