input:
  whatever:
    required: true
runs:
  using: composite
  steps:

  - run: |
      echo ${{ whatever }}
      echo whatever=$whatever >> $GITHUB_ENV
      echo "Now $whatever is also part of your env"
